algo = input('Digite algo: ')
print('O que você digitou é numérico:', algo.isnumeric())
print('O que você digitou é alfabético:', algo.isalpha())
print('O que você digitou é numérico ou alfabético:', algo.isalnum())
print('O que você digitou é somente em letra maiuscula:', algo.isupper())
